# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


clusterName:

huggingface:
  secretName: hf-secret
  secretData:
    token: "hf_api_token"

model:
  name: &model-name deepseek3-671b
  hf_model_name: &hf-model-name deepseek-ai/DeepSeek-R1

job:
  jax_tpu_image:
    repository: 
    tag: 
  jetstream_http_image:
    repository: us-docker.pkg.dev/cloud-tpu-images/inference/jetstream-http
    tag: v0.2.3
  pathways_proxy_image:
    repository: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/proxy_server
    tag: jax-0.8.0
  pathways_rm_image:
    repository: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/server
    tag: jax-0.8.0


volumes:
  ssdMountPath: "/ssd"
  gcsMounts:
    - bucketName:
      mountPath: "/gcs"

jetstream:
  service:
    ports:
      http: 8000
      grpc: 9000

convert_hf_ckpt: true

maxtext_config:
  allow_split_physical_axes: true
  tokenizer_type: huggingface
  hf_access_token: $HF_TOKEN
  tokenizer_path: *hf-model-name
  model_name: *model-name
  use_chat_template: false
  load_parameters_path: 
  max_prefill_predict_length: 1024
  max_target_length: 1536
  async_checkpointing: false
  steps: 1
  kv_quant_axis: dkv
  ici_fsdp_parallelism: 1
  ici_autoregressive_parallelism: 1
  ici_expert_parallelism: 64
  ici_tensor_parallelism: 1
  scan_layers: false
  weight_dtype: bfloat16
  per_device_batch_size: 6
  enable_single_controller: true
  megablox: false
  sparse_matmul: false
  capacity_factor: -1.0
  attention: "dot_product"
  quantize_kvcache: true
  kv_quant_dtype: int4
  logical_axis_rules: "[[activation_batch,[data,fsdp,fsdp_transpose]],[activation_batch_no_exp,[data,fsdp,fsdp_transpose]],[activation_embed_and_logits_batch,[data,stage,fsdp,fsdp_transpose]],[activation_heads,[tensor,expert,tensor_transpose,sequence,tensor_sequence]],[activation_kv_heads,[tensor,expert,tensor_transpose,sequence,tensor_sequence]],[activation_length,[sequence]],[activation_norm_length,[tensor_sequence,sequence]],[activation_embed,[tensor,tensor_transpose]],[activation_mlp,[tensor_transpose,tensor_sequence]],[activation_kv,[tensor_transpose,tensor_sequence]],[activation_prefill_kv_batch,[data,fsdp,fsdp_transpose,expert]],[activation_kv_batch,[data,fsdp,fsdp_transpose]],[activation_kv_head_dim,[tensor_transpose,tensor_sequence]],[activation_vocab,[tensor,tensor_transpose,sequence,tensor_sequence]],[activation_stage,stage],[activation_exp,expert],[mlp,[fsdp_transpose,tensor_sequence,autoregressive]],[vocab,[tensor,tensor_transpose,tensor_sequence,autoregressive,expert]],[heads,[tensor,expert,tensor_transpose,tensor_sequence,autoregressive]],[q_heads,[tensor,expert,tensor_transpose,tensor_sequence,autoregressive]],[kv_heads,[tensor,expert,tensor_transpose,tensor_sequence,autoregressive]],[embed,[fsdp,fsdp_transpose,sequence,tensor_transpose]],[embed,[fsdp,sequence,tensor_transpose]],[embed,[fsdp,fsdp_transpose,sequence]],[embed,[fsdp,sequence]],[embed_no_exp,[fsdp,fsdp_transpose,sequence,tensor_transpose]],[embed_no_exp,[fsdp,sequence,tensor_transpose]],[embed_no_exp,[fsdp,fsdp_transpose,sequence]],[embed_no_exp,[fsdp,sequence]],[q_lora,[fsdp,sequence]],[kv_lora,[fsdp,sequence]],[norm,[tensor,tensor_transpose,tensor_sequence]],[layers,stage],[kv,[]],[kv_head_dim,[]],[cache_batch_prefill,[]],[cache_batch,[]],[cache_heads,[autoregressive,tensor,expert,tensor_transpose,tensor_sequence]],[cache_heads,[autoregressive,tensor,expert,tensor_sequence]],[cache_kv,[]],[cache_sequence,[]],[cache_scale_heads,[autoregressive,tensor,expert,tensor_sequence]],[exp,expert],[paged_kv_heads,[]],[num_pages,[tensor,expert]],[tokens_per_page,[]],[paged_kv_head_dim_size,[]]]"
  quantization: int8
  checkpoint_is_quantized: true
  enable_model_warmup: true
  checkpoint_storage_use_ocdbt: false
  checkpoint_storage_use_zarr3: false

xla_flags:
  # decode
  - --xla_jf_auto_cross_replica_sharding=False
  - --xla_jf_rematerialization_percent_shared_memory_limit=100
  - --xla_tpu_allocate_scoped_vmem_at_same_offset=True
  - --xla_tpu_alternate_memory_benefit_scaling_factor_for_large_buffers=NO_SCALE
  - --xla_tpu_async_copy_bandwidth_scaling_factor=0.9584900814663344
  - --xla_tpu_copy_elision_analysis_allowance=86107
  - --xla_tpu_copy_fusion_pad_unpad_ratio=310.3052345427081
  - --xla_tpu_copy_insertion_use_region_analysis_limit=8206
  - --xla_tpu_dot_dot_fusion=False
  - --xla_tpu_dot_dot_fusion_duplicated=True
  - --xla_tpu_enable_aggressive_broadcast_priority_update=True
  - --xla_tpu_enable_dot_strength_reduction=True
  - --xla_tpu_enable_experimental_fusion_cost_model=True
  - --xla_tpu_enable_vmem_to_vmem_dmas=False
  - --xla_tpu_enforce_prefetch_fifo_order=False
  - --xla_tpu_layout_use_dot_grouping=True
  - --xla_tpu_memory_bound_loop_optimizer_options=enabled:true
  - --xla_tpu_msa_inefficient_use_to_copy_ratio=0.9413217726181875
  - --xla_tpu_nd_short_transfer_max_chunks=761
  - --xla_tpu_order_dot_after_layout=False
  - --xla_tpu_perform_spmd_cse_prevention=False
  - --xla_tpu_prefetch_interval_picker_size_override=50324332
  - --xla_tpu_reduce_loop_fusion_dup_with_unfusable_user=False
  - --xla_tpu_rwb_fusion=True
  - --xla_tpu_scavenge_vmem_for_fusions=False
  - --xla_tpu_scoped_vmem_limit_kib=23201
  - --xla_tpu_sliced_prefetch_max_slices=0
  - --xla_tpu_use_lp_llo_scheduler_for_dot_dot_fusions=False
  - --xla_tpu_use_repeated_instance_for_preferred_prefetch_time=True
  - --xla_tpu_vector_load_fusion_window=1614
  - --xla_tpu_vector_store_fusion_window=2903
  - --xla_vf_vmem_enable_cross_program_prefetch_freeing=False
  - --xla_vf_vmem_max_outstanding_evictions=145
  - --xla_vf_vmem_max_outstanding_prefetches=160
  - --xla_vf_vmem_max_overlap_to_mem_size_async_copy_ratio=24.84395238653079
  - --xla_vf_vmem_max_repacks=35
  - --xla_vf_vmem_max_retries=7
  - --xla_vf_vmem_min_overlap_to_async_copy_ratio=1.97479565169615
  - --xla_vf_vmem_preferred_overlap_to_async_copy_ratio=12.940235149405048
  # prefill
  - --xla_jf_auto_cross_replica_sharding=False
  - --xla_jf_rematerialization_percent_shared_memory_limit=99
  - --xla_tpu_allocate_scoped_vmem_at_same_offset=True
  - --xla_tpu_alternate_memory_benefit_scaling_factor_for_large_buffers=NO_SCALE
  - --xla_tpu_async_copy_bandwidth_scaling_factor=1.9995044414598915
  - --xla_tpu_copy_elision_analysis_allowance=373240
  - --xla_tpu_copy_fusion_pad_unpad_ratio=487.8989822853075
  - --xla_tpu_copy_insertion_use_region_analysis_limit=1380
  - --xla_tpu_dot_dot_fusion=False
  - --xla_tpu_dot_dot_fusion_duplicated=False
  - --xla_tpu_enable_aggressive_broadcast_priority_update=False
  - --xla_tpu_enable_dot_strength_reduction=True
  - --xla_tpu_enable_experimental_fusion_cost_model=False
  - --xla_tpu_enable_vmem_to_vmem_dmas=True
  - --xla_tpu_enforce_prefetch_fifo_order=True
  - --xla_tpu_layout_use_dot_grouping=True
  - --xla_tpu_memory_bound_loop_optimizer_options=enabled:false
  - --xla_tpu_msa_inefficient_use_to_copy_ratio=0.7402793814891878
  - --xla_tpu_nd_short_transfer_max_chunks=8189
  - --xla_tpu_order_dot_after_layout=True
  - --xla_tpu_perform_spmd_cse_prevention=True
  - --xla_tpu_prefetch_interval_picker_size_override=58150141
  - --xla_tpu_reduce_loop_fusion_dup_with_unfusable_user=True
  - --xla_tpu_rwb_fusion=True
  - --xla_tpu_scavenge_vmem_for_fusions=False
  - --xla_tpu_scoped_vmem_limit_kib=32768
  - --xla_tpu_sliced_prefetch_max_slices=0
  - --xla_tpu_use_lp_llo_scheduler_for_dot_dot_fusions=False
  - --xla_tpu_use_repeated_instance_for_preferred_prefetch_time=False
  - --xla_tpu_vector_load_fusion_window=2
  - --xla_tpu_vector_store_fusion_window=3801
  - --xla_vf_vmem_enable_cross_program_prefetch_freeing=False
  - --xla_vf_vmem_max_outstanding_evictions=14
  - --xla_vf_vmem_max_outstanding_prefetches=147
  - --xla_vf_vmem_max_overlap_to_mem_size_async_copy_ratio=5.097899221354412
  - --xla_vf_vmem_max_repacks=34
  - --xla_vf_vmem_max_retries=6
  - --xla_vf_vmem_min_overlap_to_async_copy_ratio=3.787897577195897
  - --xla_vf_vmem_preferred_overlap_to_async_copy_ratio=13.805435643567911
  
