apiVersion: v1
kind: PersistentVolume
metadata:
  name: lustre-pv
spec:
  storageClassName: ""
  capacity:
    storage: <INSTANCE CAPACITY SIZE>
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: default
    name: lustre-volume
  csi:
    driver: lustre.csi.storage.gke.io
    volumeHandle: <PROJECT_ID>/<ZONE>/<LUSTRE_INSTANCE_NAME>
    volumeAttributes:
      ip: <INSTANCE IP>
      filesystem: <FILE SYSTEM NAME>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lustre-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: <INSTANCE CAPACITY SIZE>
  volumeName: lustre-pv
  storageClassName: ""